### ISSUE TITLE
报错如下

### ISSUE THREAD

**Issue by Misakio** [leyuwei/MillionHeroHybridAssist#1]
可以正常截图**
但是报如下错误：

截图分析过程中出现故障，请确认设备是否连接正确（投屏正常），网络是否通畅！

-----------------------------
请在答题开始前运行程序，
答题开始的时候按Enter预测答案

看了下截图是正常的~请指教

**Comment by leyuwei** [comment]
您好：
    请问您是在今天的答题中遇到这个问题的吗？如果是的话，这个问题我已经在下一个版本中修复了，是由百度OCR识别漏字情况下+某个数组初始化位置没放对造成的。新版本我明天上传，感谢您的关注~




在2018年2月13日 23:52，Misaki<notifications@github.com> 写道：

可以正常截图**
但是报如下错误：

截图分析过程中出现故障，请确认设备是否连接正确（投屏正常），网络是否通畅！

请在答题开始前运行程序，
答题开始的时候按Enter预测答案

看了下截图是正常的~请指教

**Comment by Misakio** [comment]
是的~我还测试了一下 原来不是我的问题
